version: '3.8'

services:
  postgres:
    image: postgres:17-alpine  # Versão leve do PostgreSQL
    container_name: meu_postgres  # Nome do container
    environment:
      POSTGRES_DB: secretaria       # Nome do banco de dados (criado automaticamente)
      POSTGRES_USER: postgres     # Usuário padrão
      POSTGRES_PASSWORD: root # Senha do usuário
    ports:
      - "5432:5432"  # Expõe a porta padrão do PostgreSQL (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados
    healthcheck: # Adicionei healthcheck para PostgreSQL
      test: [ "CMD-SHELL", "pg_isready -U postgres -d secretaria" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servidor MinIO (S3 compatível)
  minio:
    image: minio/minio
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: admin           # Usuário padrão
      MINIO_ROOT_PASSWORD: senhaadmin  # Senha padrão
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data: