version: '3.8'

services:
  postgres:
    image: postgres:17-alpine  # Versão leve do PostgreSQL
    container_name: meu_postgres  # Nome do container
    environment:
      POSTGRES_DB: secretaria       # Nome do banco de dados (criado automaticamente)
      POSTGRES_USER: postgres     # Usuário padrão
      POSTGRES_PASSWORD: root # Senha do usuário
    ports:
      - "5432:5432"  # Expõe a porta padrão do PostgreSQL (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados
    healthcheck: # Adicionei healthcheck para PostgreSQL
      test: [ "CMD-SHELL", "pg_isready -U postgres -d secretaria" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servidor MinIO (S3 compatível)
  minio:
    image: minio/minio
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: senhaadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-client:
    image: minio/mc
    container_name: minio_client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set myminio http://minio:9000 admin senhaadmin;
        mc mb myminio/fotos-pessoa || true;
        exit 0;

volumes:
  postgres_data:
  minio_data: