version: '3.8'

services:
  postgres:
    image: postgres:17-alpine  # Versão leve do PostgreSQL
    container_name: meu_postgres  # Nome do container
    environment:
      POSTGRES_DB: secretaria       # Nome do banco de dados (criado automaticamente)
      POSTGRES_USER: postgres     # Usuário padrão
      POSTGRES_PASSWORD: root # Senha do usuário
    ports:
      - "5432:5432"  # Expõe a porta padrão do PostgreSQL (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados
    healthcheck: # Adicionei healthcheck para PostgreSQL
      test: [ "CMD-SHELL", "pg_isready -U postgres -d secretaria" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: senhaadmin
    ports:
      - "9000:9000"  # API do MinIO
      - "9001:9001"  # Console de administração do MinIO
    volumes:
      - minio_data:/data  # Volume persistente para dados do MinIO
    command: server /data --console-address ":9001"  # Inicializa o MinIO no caminho /data com console na porta 9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]  # Verifica a saúde do serviço MinIO
      interval: 10s  # Intervalo entre os testes de saúde
      timeout: 5s  # Timeout para o teste de saúde
      retries: 5  # Número de tentativas antes de considerar o serviço como não saudável

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "9002:9002"  # A URL externa que será mapeada
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração do Nginx
    depends_on:
      - minio


  backend:
    build:
      context: ./  # Raiz do projeto
      dockerfile: Dockerfile  # Dockerfile está na raiz
    container_name: meu_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/secretaria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: senhaadmin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy


volumes:
  postgres_data:
  minio_data: